import "./globals.css";
import { Gilda_Display, Barlow, Barlow_Condensed } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ContextProvider } from "./context";
import { Suspense } from "react";
import Loading from "./loading";

const gilda = Gilda_Display({
  subsets: ["latin"],
  variable: "--font-gilda",
  weight: ["400"],
});
const barlow = Barlow({
  subsets: ["latin"],
  variable: "--font-barlow",
  weight: ["400"],
});
const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  variable: "--font-barlowCondansed",
  weight: ["400"],
});

export const metadata = {
  title: "LuxeVista Hotel",
  description:
    "Generated by create next appDiscover luxury accommodations and exceptional service at Your Hotel. Enjoy a comfortable stay and excellent amenities for both business and leisure travelers",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${gilda.variable} ${barlow.variable} ${barlowCondensed.variable}`}
    >
      <body>
        <Navbar />
        <Suspense fallback={<Loading />}>
          <ContextProvider>{children}</ContextProvider>
        </Suspense>
        <Footer />
      </body>
    </html>
  );
}
